#:schema node_modules/wrangler/config-schema.json
name = "tempemaildonotshowme"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "EMAIL_STORE"
id = "85761845d9484c839f6a0ebd0a2ff029"

[[kv_namespaces]]
binding = "ANALYTICS_STORE"
id = "dc5229897cc14b2e8e2f348aa2928173"
